name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: rodrigoarias/auto-label-per-user@v1.0.0
        with:
             git-token: ${{ secrets.MY_GITHUB_TOKEN }}
             default-label: "hacktober-accepted"
             user-team-map: |
              {
                "NotKyoyo":"auto-merge"
              }
        
